-- begin CATALOG_VEHICLE_MODEL
create unique index IDX_CATALOG_VEHICLE_MODEL_UK_NAME on CATALOG_VEHICLE_MODEL (NAME) where DELETE_TS is null ^
-- end CATALOG_VEHICLE_MODEL
-- begin CATALOG_TARIFF_BASE
create unique index IDX_CATALOG_TARIFF_BASE_UK_ORDER_ on CATALOG_TARIFF_BASE (ORDER_) where DELETE_TS is null ^
create unique index IDX_CATALOG_TARIFF_BASE_UK_VEHICLE on CATALOG_TARIFF_BASE (VEHICLE) where DELETE_TS is null ^
-- end CATALOG_TARIFF_BASE
